# Generated by Django 4.0.6 on 2022-07-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('score', models.CharField(max_length=200)),
            ],
        ),
    ]
