# Generated by Django 4.0.6 on 2022-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurVitae', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('display', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
