# Generated by Django 4.0.6 on 2022-07-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurVitae', '0003_projects_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, default='/static/Projects/assets/img/Portfolio/default.jpg', null=True, upload_to='projects_images'),
        ),
    ]
